#pragma once

#include <raylib.h>

// == NUMBER SETTINGS ==
#define WIN_W 1280
#define WIN_H 720
#define WIN_FLAGS FLAG_WINDOW_RESIZABLE
#define PEN_RADIUS 5
#define TARGET_FPS 69420
#define COLOR_PICKER_W 50
#define COLOR_PICKER_H 50

// == STRING/PATH RELATED SETTINGS ==
#define WIN_TITLE "Paint"

// == COLOR RELATED SETTINGS ==
#define WIN_BG_COLOR BLACK
#define DEFAULT_DRAWING_COLOR WHITE

// == KEY RELATED SETTINGS ==
#define EXIT_KEY KEY_NULL
#define ERASER_KEY KEY_E
#define CLEAR_CANVAS_KEY KEY_DELETE
#define DRAW_KEY MOUSE_BUTTON_LEFT
#define RADIUS_PLUS_KEY KEY_EQUAL
#define RADIUS_MINUS_KEY KEY_MINUS
#define RADIUS_ZERO_KEY KEY_ZERO
